<?php

namespace LaraAreaSeo\Services;

use Illuminate\Support\Arr;
use LaraAreaSeo\Cache\CachedSeo;

class SeoRouteService extends BaseService
{
    protected function fixDataForCreate($data)
    {
        if (!empty($data['uris'])) {
            $data['with']['uris'] = Arr::pull($data, 'uris');
        }
        if (!empty($data['tags'])) {
            $data['tags'] = array_filter($data['tags']);
        }
        return parent::fixDataForCreate($data); // TODO: Change the autogenerated stub
    }

    protected function fixDataForUpdate($item, $data)
    {
        if (!empty($data['uris'])) {
            $data['with']['uris'] = Arr::pull($data, 'uris');
        }
        return parent::fixDataForUpdate($item, $data); // TODO: Change the autogenerated stub
    }

    /**
     * @param $item
     * @param $with
     */
    public function updateRelations($item, $with)
    {
        if (! empty($with['uris'])) {
            $uris = $with['uris'];
            $uris = array_unique($uris);
            $item->seo_uris()->whereNotIn('uri', $uris)->delete();
            $seoUris = $item->seo_uris()->pluck('seo_uris.uri')->all();
            foreach ($uris as $uri) {
                if (in_array($uri, $seoUris)) {
                    continue;
                }
                $item->seo_uris()->create(['uri' => $uri]);
            }
        }
    }

    /**
     * @param $item
     */
    protected function itemSaved($item)
    {
        CachedSeo::updateSeoRoutes();
    }

    /**
     * @param $item
     */
    protected function itemDeleted($item)
    {
        CachedSeo::updateSeoRoutes();
    }
}
